### ISSUE TITLE
Favicon is all white, which is not visible on white themed browsers

### ISSUE THREAD

**Issue by KunalSin9h** [coptit/club-website#28]
## Solution
1. Create a png of black background with white logo
2. use favion generators to generate favicon of different sizes
3. update the code.

**Comment by KunalSin9h** [comment]
fix

**Comment by srijan0412** [comment]
Fixed ?

**Comment by naaam-h-siddhu** [comment]
I'll fix it 2moro only

**Comment by KunalSin9h** [comment]
it is fixed?

**Comment by naaam-h-siddhu** [comment]
ok🌚
